# Generated by Django 5.0 on 2023-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_fa', models.TextField(max_length=30)),
                ('firstname_en', models.TextField(max_length=30)),
                ('lastname_fa', models.TextField(max_length=30)),
                ('lastname_en', models.TextField(max_length=30)),
                ('position', models.TextField(max_length=30)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
