# Generated by Django 5.0 on 2023-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
